# Generated by Django 2.2.12 on 2022-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
